title: Referral Tesla Italia
description: Referral Tesla 2026 - Ottieni 1000 km Supercharger gratis o 500â‚¬ di sconto con il codice referral nicola722048
url: https://petrosinic.github.io/referral-tesla/
baseurl: /referral-tesla
